apiVersion: batch/v1
kind: Job
metadata:
  name: minigo-gpu-player
spec:
  parallelism: $NUM_K8S_NODES
  completions: 200000
  template:
    metadata:
      name: gpu-player
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: job-label
                operator: In
                values:
                - minigo-gpu-player
            topologyKey: kubernetes.io/hostname
      containers:
      - name: player
        image: gcr.io/$PROJECT/$GPU_PLAYER_CONTAINER:$VERSION_TAG
        imagePullPolicy: Always
        resources:
          limits:
            beta.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - name: service-credentials
          mountPath: /etc/credentials
        - mountPath: /usr/local/bin/nvidia
          name: nvidia-debug-tools
        - mountPath: /usr/local/nvidia/lib64
          name: nvidia-libraries
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/service-account.json
        - name: BUCKET_NAME
          value: $BUCKET_NAME
        - name: BOARD_SIZE
          value: "$BOARD_SIZE"
        securityContext:
          privileged: true
      volumes:
      - name: service-credentials
        secret:
          secretName: $SERVICE_ACCOUNT-creds
      - hostPath:
          path: /home/kubernetes/bin/nvidia/bin
        name: nvidia-debug-tools
      - hostPath:
          path: /home/kubernetes/bin/nvidia/lib
        name: nvidia-libraries
      restartPolicy: OnFailure
